Typed array
microavia/messgen pull request #74
Opened 2023-09-01 13:04 UTC by meded90

2023-09-04 10:46 UTC, Zemledelec commented on .gitignore
> +tests/js/MessgenHelper.ts
На будущее, мы уже, ts не пишем:)

2023-09-04 10:47 UTC, Zemledelec commented on .run/generate-ts-with-typed-array.run.xml
Может .run в игнор добавить?

2023-09-04 10:50 UTC, Zemledelec commented on port/js/src/messgen.js
> +        typedArray: Uint8Array
Я бы всетаки это вынес в отдельную (генеральную) структуру, есть аргументы против?

2023-09-04 10:54 UTC, Zemledelec requested changes
Посмтоти пожалуйста вопросы.

2023-09-04 11:08 UTC, meded90 commented on .gitignore
> +tests/js/MessgenHelper.ts
Это не ипорт, а игнор с генерированного файла

2023-09-04 11:09 UTC, meded90 commented on .run/generate-ts-with-typed-array.run.xml
я специально оставил чтобы удобно из иде было всем запускать, но могу удалить

2023-09-04 11:11 UTC, meded90 commented on port/js/src/messgen.js
> +        typedArray: Uint8Array
изо одного ифа дублировать всю логику мне кажется излишне. там и так уже десериализация масивов происходит 2 раза. так будет 4

2023-09-04 11:13 UTC, Zemledelec commented on port/js/src/messgen.js
> +        typedArray: Uint8Array
Прошу прощения, затупил, все и так прекрасно!

2023-09-04 11:14 UTC, meded90 commented on .run/generate-ts-with-typed-array.run.xml
убрал

2023-09-06 05:54 UTC, Zemledelec approved these changes

2023-09-06 05:54 UTC, merged